version: '2'

services:
    nginx:
        image: nginx:1.11.3-alpine
        volumes:
            - ./html:/var/www/html:ro
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        ports:
            - 80:80
            - 443:443
        links:
            - app
    
    app:
        build: 
            context: .
            dockerfile: django-alpine.dockerfile
        image: myapp_django:1.10-alpine
        volumes:
            - ./html/project_files:/app
        links:
            - db
    
    db:
        image: mariadb:10.1.16
        volumes:
            - /var/lib/mysql:/var/lib/mysql
        env_file:
            - ./mariadb.config.env
